[package]
name = "htpp"
version = "0.1.1"
edition = "2021"
authors=["Basel"]
description="A simple, fast, and secure http parser. It adheres strictly to the http specification, which is intentional as to be efficient and prevent possible http related attacks. It only supports http 1.1 but support for http 2.0 is planned"
keywords=["http", "parser"]
repository="https://github.com/Albassel/htpp"
license="MIT"
exclude = [
    "benches/parse.rs",
    "src/tests.rs",
    ".gitignore",
    "README.md"
]
#documentation="URL of package docs"


[[bench]]
harness = false
path = "benches/parse.rs"
name = "parse"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"

